name: CI

on:
  push:
    tags:
      - build-windows-*

jobs:  
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        where git
        export PATH=$PATH:"c/Program Files/Git/bin"
        echo $PATH
        cd nix
        export CFLAGS="-O3"
        export CXXFLAGS="-O3"
        export BUILD_CFG="Release"
        python3.8 build-all.py
        cd ..
        mv build/Linux/x86_64/build/ifcopenshell/executables/IfcConvert IfcConvert
        zip IfcConvert.zip IfcConvert
      shell: bash
    - uses: actions/upload-artifact@v1
      with:
        name: IfcConvert
        path: IfcConvert.zip